version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "09:00"
    timezone: Europe/Dublin
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: html-proofer
    versions:
    - 3.18.8
    - 3.19.0
  - dependency-name: github-pages
    versions:
    - "210"
