# Site settings
title: Zero Waste Sud Grand Paris
description: >- # this means to ignore newlines until "baseurl:"
  Groupe local de Zero Waste France opérant sur le bassin sud-ouest
  du grand Paris (Malakoff, Vanves, Issy-Les-Moulineaux, Montrouge,
  Chatillon, Clamart).
keywords: Zero Waste
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.zerowastesgp.fr" # the base hostname & protocol for your site, e.g. http://example.com

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Build settings
markdown: kramdown
excerpt_separator: "<!--more-->"

sass:
  style: compressed

# Outputting
permalink: :year/:month/:day/:title/
timezone: Europe/Paris
