# Site settings
title: Zero Waste Sud Grand Paris
email: sudgrandparis@zerowastefrance.org
description: >- # this means to ignore newlines until "baseurl:"
  Groupe local de Zero Waste France opérant sur le bassin sud-ouest
  du grand Paris (Malakoff, Vanves, Issy-Les-Moulineaux, Montrouge,
  Chatillon, Clamart).
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.zerowastesgp.fr" # the base hostname & protocol for your site, e.g. http://example.com
github_username: zerowastesgp
facebook_username: ZeroWasteSudGrandParis
instagram_username: zerowaste_sudgrandparis
email: sudgrandparis@zerowastefrance.org

avatar: yes
avatar_img_path: /assets/images/main-logo.png

front_img: yes
front_img_path: /assets/images/landing-page-landscape.jpg

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
